# Generated by Django 3.1.1 on 2020-10-06 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rooms',
            options={'ordering': ['numbers_of_rooms']},
        ),
        migrations.RenameField(
            model_name='rooms',
            old_name='numbers_rooms',
            new_name='numbers_of_rooms',
        ),
        migrations.RenameField(
            model_name='rooms',
            old_name='numbers_students',
            new_name='numbers_of_students',
        ),
    ]
